# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.srcs/sources_1/bd/logictools/ip/logictools_mb_2/logictools_mb_2.xci
# IP: The module: 'logictools_mb_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_2/logictools_mb_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_2/logictools_mb_2_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_2/logictools_mb_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.srcs/sources_1/bd/logictools/ip/logictools_mb_2/logictools_mb_2.xci
# IP: The module: 'logictools_mb_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_2/logictools_mb_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_2/logictools_mb_2_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_2/logictools_mb_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
