# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/constraints/logictools.xdc

# Block Designs: bd/logictools/logictools.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools || ORIG_REF_NAME==logictools} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_pb_0/logictools_concat_pb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_pb_0 || ORIG_REF_NAME==logictools_concat_pb_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_debouncer_0_0/logictools_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_debouncer_0_0 || ORIG_REF_NAME==logictools_debouncer_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_debouncer_1_0/logictools_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_debouncer_1_0 || ORIG_REF_NAME==logictools_debouncer_1_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_debouncer_2_0/logictools_debouncer_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_debouncer_2_0 || ORIG_REF_NAME==logictools_debouncer_2_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_debouncer_3_0/logictools_debouncer_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_debouncer_3_0 || ORIG_REF_NAME==logictools_debouncer_3_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_pb_0_0/logictools_slice_pb_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_pb_0_0 || ORIG_REF_NAME==logictools_slice_pb_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_pb_1_0/logictools_slice_pb_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_pb_1_0 || ORIG_REF_NAME==logictools_slice_pb_1_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_pb_2_0/logictools_slice_pb_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_pb_2_0 || ORIG_REF_NAME==logictools_slice_pb_2_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_pb_3_0/logictools_slice_pb_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_pb_3_0 || ORIG_REF_NAME==logictools_slice_pb_3_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_iop_interrupts_0/logictools_iop_interrupts_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_iop_interrupts_0 || ORIG_REF_NAME==logictools_iop_interrupts_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_0/logictools_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_0 || ORIG_REF_NAME==logictools_concat_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_dff_en_reset_vector_0_0/logictools_dff_en_reset_vector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_dff_en_reset_vector_0_0 || ORIG_REF_NAME==logictools_dff_en_reset_vector_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_gpio_0/logictools_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_gpio_0 || ORIG_REF_NAME==logictools_gpio_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_iic_0/logictools_iic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_iic_0 || ORIG_REF_NAME==logictools_iic_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_intc_0/logictools_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_intc_0 || ORIG_REF_NAME==logictools_intc_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_intr_0/logictools_intr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_intr_0 || ORIG_REF_NAME==logictools_intr_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_io_switch_0/logictools_io_switch_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_io_switch_0 || ORIG_REF_NAME==logictools_io_switch_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_dlmb_v10_0/logictools_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_dlmb_v10_0 || ORIG_REF_NAME==logictools_dlmb_v10_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_ilmb_v10_0/logictools_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_ilmb_v10_0 || ORIG_REF_NAME==logictools_ilmb_v10_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_lmb_bram_0/logictools_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_lmb_bram_0 || ORIG_REF_NAME==logictools_lmb_bram_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_lmb_bram_if_cntlr_0/logictools_lmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_lmb_bram_if_cntlr_0 || ORIG_REF_NAME==logictools_lmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_logic_1_0/logictools_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_logic_1_0 || ORIG_REF_NAME==logictools_logic_1_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_0/logictools_mb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_0 || ORIG_REF_NAME==logictools_mb_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_bram_ctrl_0/logictools_mb_bram_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_bram_ctrl_0 || ORIG_REF_NAME==logictools_mb_bram_ctrl_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_microblaze_0_axi_periph_imp_xbar_0/logictools_microblaze_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_microblaze_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==logictools_microblaze_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_microblaze_0_axi_periph_0/logictools_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_microblaze_0_axi_periph_0 || ORIG_REF_NAME==logictools_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_rst_clk_wiz_1_100M_0/logictools_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==logictools_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_spi_0/logictools_spi_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_spi_0 || ORIG_REF_NAME==logictools_spi_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_timer_0/logictools_timer_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_timer_0 || ORIG_REF_NAME==logictools_timer_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_1/logictools_concat_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_1 || ORIG_REF_NAME==logictools_concat_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_dff_en_reset_vector_0_1/logictools_dff_en_reset_vector_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_dff_en_reset_vector_0_1 || ORIG_REF_NAME==logictools_dff_en_reset_vector_0_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_gpio_1/logictools_gpio_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_gpio_1 || ORIG_REF_NAME==logictools_gpio_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_iic_1/logictools_iic_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_iic_1 || ORIG_REF_NAME==logictools_iic_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_intc_1/logictools_intc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_intc_1 || ORIG_REF_NAME==logictools_intc_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_intr_1/logictools_intr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_intr_1 || ORIG_REF_NAME==logictools_intr_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_io_switch_1/logictools_io_switch_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_io_switch_1 || ORIG_REF_NAME==logictools_io_switch_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_dlmb_v10_1/logictools_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_dlmb_v10_1 || ORIG_REF_NAME==logictools_dlmb_v10_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_ilmb_v10_1/logictools_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_ilmb_v10_1 || ORIG_REF_NAME==logictools_ilmb_v10_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_lmb_bram_1/logictools_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_lmb_bram_1 || ORIG_REF_NAME==logictools_lmb_bram_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_lmb_bram_if_cntlr_1/logictools_lmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_lmb_bram_if_cntlr_1 || ORIG_REF_NAME==logictools_lmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_logic_1_1/logictools_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_logic_1_1 || ORIG_REF_NAME==logictools_logic_1_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_1/logictools_mb_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_1 || ORIG_REF_NAME==logictools_mb_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_bram_ctrl_1/logictools_mb_bram_ctrl_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_bram_ctrl_1 || ORIG_REF_NAME==logictools_mb_bram_ctrl_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_microblaze_0_axi_periph_imp_xbar_1/logictools_microblaze_0_axi_periph_imp_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_microblaze_0_axi_periph_imp_xbar_1 || ORIG_REF_NAME==logictools_microblaze_0_axi_periph_imp_xbar_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_microblaze_0_axi_periph_1/logictools_microblaze_0_axi_periph_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_microblaze_0_axi_periph_1 || ORIG_REF_NAME==logictools_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_rst_clk_wiz_1_100M_1/logictools_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==logictools_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_spi_1/logictools_spi_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_spi_1 || ORIG_REF_NAME==logictools_spi_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_timer_1/logictools_timer_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_timer_1 || ORIG_REF_NAME==logictools_timer_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_fsm_bram_ctrl_0/logictools_fsm_bram_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_fsm_bram_ctrl_0 || ORIG_REF_NAME==logictools_fsm_bram_ctrl_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_fsm_bram_rst_addr_0/logictools_fsm_bram_rst_addr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_fsm_bram_rst_addr_0 || ORIG_REF_NAME==logictools_fsm_bram_rst_addr_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_fsm_controller_0/logictools_fsm_controller_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_fsm_controller_0 || ORIG_REF_NAME==logictools_fsm_controller_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_fsm_generator_mem_0/logictools_fsm_generator_mem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_fsm_generator_mem_0 || ORIG_REF_NAME==logictools_fsm_generator_mem_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_fsm_io_switch_0/logictools_fsm_io_switch_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_fsm_io_switch_0 || ORIG_REF_NAME==logictools_fsm_io_switch_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_addrB_0/logictools_concat_addrB_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_addrB_0 || ORIG_REF_NAME==logictools_concat_addrB_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_fsmout_0/logictools_concat_fsmout_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_fsmout_0 || ORIG_REF_NAME==logictools_concat_fsmout_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_constant_17bit_0_0/logictools_constant_17bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_constant_17bit_0_0 || ORIG_REF_NAME==logictools_constant_17bit_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_constant_32bit_0_0/logictools_constant_32bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_constant_32bit_0_0 || ORIG_REF_NAME==logictools_constant_32bit_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_logic_0_0/logictools_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_logic_0_0 || ORIG_REF_NAME==logictools_logic_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_logic_2bit_0_0/logictools_logic_2bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_logic_2bit_0_0 || ORIG_REF_NAME==logictools_logic_2bit_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_logic_4bit_0_0/logictools_logic_4bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_logic_4bit_0_0 || ORIG_REF_NAME==logictools_logic_4bit_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_dout_31_13_0/logictools_slice_dout_31_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_dout_31_13_0 || ORIG_REF_NAME==logictools_slice_dout_31_13_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_dout_4_0_0/logictools_slice_dout_4_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_dout_4_0_0 || ORIG_REF_NAME==logictools_slice_dout_4_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_dout_8_5_0/logictools_slice_dout_8_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_dout_8_5_0 || ORIG_REF_NAME==logictools_slice_dout_8_5_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mux_vector_0_0/logictools_mux_vector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mux_vector_0_0 || ORIG_REF_NAME==logictools_mux_vector_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_cdma_0_0/logictools_axi_cdma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_cdma_0_0 || ORIG_REF_NAME==logictools_axi_cdma_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_mem_intercon_imp_xbar_0/logictools_axi_mem_intercon_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_mem_intercon_imp_xbar_0 || ORIG_REF_NAME==logictools_axi_mem_intercon_imp_xbar_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_mem_intercon_imp_auto_ds_0/logictools_axi_mem_intercon_imp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_mem_intercon_imp_auto_ds_0 || ORIG_REF_NAME==logictools_axi_mem_intercon_imp_auto_ds_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_mem_intercon_imp_auto_pc_0/logictools_axi_mem_intercon_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_mem_intercon_imp_auto_pc_0 || ORIG_REF_NAME==logictools_axi_mem_intercon_imp_auto_pc_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_mem_intercon_imp_auto_ds_1/logictools_axi_mem_intercon_imp_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_mem_intercon_imp_auto_ds_1 || ORIG_REF_NAME==logictools_axi_mem_intercon_imp_auto_ds_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_mem_intercon_imp_auto_ds_2/logictools_axi_mem_intercon_imp_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_mem_intercon_imp_auto_ds_2 || ORIG_REF_NAME==logictools_axi_mem_intercon_imp_auto_ds_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_mem_intercon_0/logictools_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_mem_intercon_0 || ORIG_REF_NAME==logictools_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_boolean_data_sel_0/logictools_boolean_data_sel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_boolean_data_sel_0 || ORIG_REF_NAME==logictools_boolean_data_sel_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_bit24_0_0/logictools_bit24_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_bit24_0_0 || ORIG_REF_NAME==logictools_bit24_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_boolean_generator_0/logictools_boolean_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_boolean_generator_0 || ORIG_REF_NAME==logictools_boolean_generator_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_0_0/logictools_concat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_0_0 || ORIG_REF_NAME==logictools_concat_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mux_vector_0_1/logictools_mux_vector_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mux_vector_0_1 || ORIG_REF_NAME==logictools_mux_vector_0_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_data_0_0/logictools_slice_data_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_data_0_0 || ORIG_REF_NAME==logictools_slice_data_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_data_1_0/logictools_slice_data_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_data_1_0 || ORIG_REF_NAME==logictools_slice_data_1_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_tri_0_0/logictools_slice_tri_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_tri_0_0 || ORIG_REF_NAME==logictools_slice_tri_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_controllers_reg_0/logictools_controllers_reg_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_controllers_reg_0 || ORIG_REF_NAME==logictools_controllers_reg_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_controls_input_0/logictools_controls_input_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_controls_input_0 || ORIG_REF_NAME==logictools_controls_input_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_dff_en_reset_vector_0_2/logictools_dff_en_reset_vector_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_dff_en_reset_vector_0_2 || ORIG_REF_NAME==logictools_dff_en_reset_vector_0_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_distributor_arduino_gpio_0/logictools_distributor_arduino_gpio_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_distributor_arduino_gpio_0 || ORIG_REF_NAME==logictools_distributor_arduino_gpio_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_func_sel_concat_0/logictools_func_sel_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_func_sel_concat_0 || ORIG_REF_NAME==logictools_func_sel_concat_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_function_sel_0/logictools_function_sel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_function_sel_0 || ORIG_REF_NAME==logictools_function_sel_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_intc_2/logictools_intc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_intc_2 || ORIG_REF_NAME==logictools_intc_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_interface_switch_0/logictools_interface_switch_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_interface_switch_0 || ORIG_REF_NAME==logictools_interface_switch_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_intr_2/logictools_intr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_intr_2 || ORIG_REF_NAME==logictools_intr_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_dlmb_v10_2/logictools_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_dlmb_v10_2 || ORIG_REF_NAME==logictools_dlmb_v10_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_ilmb_v10_2/logictools_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_ilmb_v10_2 || ORIG_REF_NAME==logictools_ilmb_v10_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_lmb_bram_2/logictools_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_lmb_bram_2 || ORIG_REF_NAME==logictools_lmb_bram_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_lmb_bram_if_cntlr_2/logictools_lmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_lmb_bram_if_cntlr_2 || ORIG_REF_NAME==logictools_lmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_logic_1_2/logictools_logic_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_logic_1_2 || ORIG_REF_NAME==logictools_logic_1_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_2/logictools_mb_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_2 || ORIG_REF_NAME==logictools_mb_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_axi_periph_imp_xbar_0/logictools_mb_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_axi_periph_imp_xbar_0 || ORIG_REF_NAME==logictools_mb_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_axi_periph_imp_auto_cc_0/logictools_mb_axi_periph_imp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_axi_periph_imp_auto_cc_0 || ORIG_REF_NAME==logictools_mb_axi_periph_imp_auto_cc_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_axi_periph_imp_auto_cc_1/logictools_mb_axi_periph_imp_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_axi_periph_imp_auto_cc_1 || ORIG_REF_NAME==logictools_mb_axi_periph_imp_auto_cc_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_axi_periph_0/logictools_mb_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_axi_periph_0 || ORIG_REF_NAME==logictools_mb_axi_periph_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_bram_ctrl_2/logictools_mb_bram_ctrl_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_bram_ctrl_2 || ORIG_REF_NAME==logictools_mb_bram_ctrl_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_addrB_1/logictools_concat_addrB_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_addrB_1 || ORIG_REF_NAME==logictools_concat_addrB_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_constant_16bit_0_0/logictools_constant_16bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_constant_16bit_0_0 || ORIG_REF_NAME==logictools_constant_16bit_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_constant_2bit_0_0/logictools_constant_2bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_constant_2bit_0_0 || ORIG_REF_NAME==logictools_constant_2bit_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_constant_32bit_0_1/logictools_constant_32bit_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_constant_32bit_0_1 || ORIG_REF_NAME==logictools_constant_32bit_0_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_constant_4bit_0_0/logictools_constant_4bit_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_constant_4bit_0_0 || ORIG_REF_NAME==logictools_constant_4bit_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_logic_0_1/logictools_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_logic_0_1 || ORIG_REF_NAME==logictools_logic_0_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_pattern_control_0/logictools_pattern_control_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_pattern_control_0 || ORIG_REF_NAME==logictools_pattern_control_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_pattern_data_bram_ctrl_0/logictools_pattern_data_bram_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_pattern_data_bram_ctrl_0 || ORIG_REF_NAME==logictools_pattern_data_bram_ctrl_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_pattern_generator_mem_tri_0/logictools_pattern_generator_mem_tri_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_pattern_generator_mem_tri_0 || ORIG_REF_NAME==logictools_pattern_generator_mem_tri_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_pattern_mem_data_0/logictools_pattern_mem_data_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_pattern_mem_data_0 || ORIG_REF_NAME==logictools_pattern_mem_data_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_pattern_nsamples_0/logictools_pattern_nsamples_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_pattern_nsamples_0 || ORIG_REF_NAME==logictools_pattern_nsamples_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_pattern_tri_bram_ctrl_0/logictools_pattern_tri_bram_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_pattern_tri_bram_ctrl_0 || ORIG_REF_NAME==logictools_pattern_tri_bram_ctrl_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_pattern_data_0/logictools_slice_pattern_data_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_pattern_data_0 || ORIG_REF_NAME==logictools_slice_pattern_data_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_slice_pattern_tri_0/logictools_slice_pattern_tri_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_slice_pattern_tri_0 || ORIG_REF_NAME==logictools_slice_pattern_tri_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_rst_clk_wiz_1_100M_2/logictools_rst_clk_wiz_1_100M_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_rst_clk_wiz_1_100M_2 || ORIG_REF_NAME==logictools_rst_clk_wiz_1_100M_2} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_dma_0_0/logictools_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_dma_0_0 || ORIG_REF_NAME==logictools_axi_dma_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_mem_intercon_1_imp_auto_pc_0/logictools_axi_mem_intercon_1_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_mem_intercon_1_imp_auto_pc_0 || ORIG_REF_NAME==logictools_axi_mem_intercon_1_imp_auto_pc_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axi_mem_intercon_1_0/logictools_axi_mem_intercon_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axi_mem_intercon_1_0 || ORIG_REF_NAME==logictools_axi_mem_intercon_1_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_axis_data_fifo_0_0/logictools_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_axis_data_fifo_0_0 || ORIG_REF_NAME==logictools_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_arduino_0/logictools_concat_arduino_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_arduino_0 || ORIG_REF_NAME==logictools_concat_arduino_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_concat_tkeep_0/logictools_concat_tkeep_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_concat_tkeep_0 || ORIG_REF_NAME==logictools_concat_tkeep_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_constant_24bits_0_0/logictools_constant_24bits_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_constant_24bits_0_0 || ORIG_REF_NAME==logictools_constant_24bits_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_constant_tstrb_0/logictools_constant_tstrb_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_constant_tstrb_0 || ORIG_REF_NAME==logictools_constant_tstrb_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_trace_cntrl_64_0_0/logictools_trace_cntrl_64_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_trace_cntrl_64_0_0 || ORIG_REF_NAME==logictools_trace_cntrl_64_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_trace_control_0/logictools_trace_control_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_trace_control_0 || ORIG_REF_NAME==logictools_trace_control_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_iop_pmoda_intr_ack_0/logictools_mb_iop_pmoda_intr_ack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_iop_pmoda_intr_ack_0 || ORIG_REF_NAME==logictools_mb_iop_pmoda_intr_ack_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_iop_pmoda_reset_0/logictools_mb_iop_pmoda_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_iop_pmoda_reset_0 || ORIG_REF_NAME==logictools_mb_iop_pmoda_reset_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_iop_pmodb_intr_ack_0/logictools_mb_iop_pmodb_intr_ack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_iop_pmodb_intr_ack_0 || ORIG_REF_NAME==logictools_mb_iop_pmodb_intr_ack_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_iop_pmodb_reset_0/logictools_mb_iop_pmodb_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_iop_pmodb_reset_0 || ORIG_REF_NAME==logictools_mb_iop_pmodb_reset_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_lcp_ar_intr_ack_0/logictools_mb_lcp_ar_intr_ack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_lcp_ar_intr_ack_0 || ORIG_REF_NAME==logictools_mb_lcp_ar_intr_ack_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mb_lcp_ar_reset_0/logictools_mb_lcp_ar_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mb_lcp_ar_reset_0 || ORIG_REF_NAME==logictools_mb_lcp_ar_reset_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_mdm_1_0/logictools_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_mdm_1_0 || ORIG_REF_NAME==logictools_mdm_1_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_ps7_0_0/logictools_ps7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_ps7_0_0 || ORIG_REF_NAME==logictools_ps7_0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_ps7_0_axi_periph_imp_xbar_0/logictools_ps7_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_ps7_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==logictools_ps7_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_ps7_0_axi_periph_imp_auto_pc_1/logictools_ps7_0_axi_periph_imp_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_ps7_0_axi_periph_imp_auto_pc_1 || ORIG_REF_NAME==logictools_ps7_0_axi_periph_imp_auto_pc_1} -quiet] -quiet

# IP: bd/logictools/ip/logictools_ps7_0_axi_periph_imp_auto_pc_0/logictools_ps7_0_axi_periph_imp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_ps7_0_axi_periph_imp_auto_pc_0 || ORIG_REF_NAME==logictools_ps7_0_axi_periph_imp_auto_pc_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_ps7_0_axi_periph_0/logictools_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_ps7_0_axi_periph_0 || ORIG_REF_NAME==logictools_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_rst_ps7_0_fclk0_0/logictools_rst_ps7_0_fclk0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_rst_ps7_0_fclk0_0 || ORIG_REF_NAME==logictools_rst_ps7_0_fclk0_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_rst_ps7_0_fclk1_0/logictools_rst_ps7_0_fclk1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_rst_ps7_0_fclk1_0 || ORIG_REF_NAME==logictools_rst_ps7_0_fclk1_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_system_interrupts_0/logictools_system_interrupts_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_system_interrupts_0 || ORIG_REF_NAME==logictools_system_interrupts_0} -quiet] -quiet

# IP: bd/logictools/ip/logictools_xlconcat_0_0/logictools_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==logictools_xlconcat_0_0 || ORIG_REF_NAME==logictools_xlconcat_0_0} -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/logictools_ooc.xdc
