# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/base/base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# XDC: c:/work/dev/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/base_ooc.xdc
