# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.srcs/sources_1/bd/logictools/ip/logictools_controllers_reg_0/logictools_controllers_reg_0.xci
# IP: The module: 'logictools_controllers_reg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_controllers_reg_0/logictools_controllers_reg_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_controllers_reg_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_controllers_reg_0/logictools_controllers_reg_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_controllers_reg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.srcs/sources_1/bd/logictools/ip/logictools_controllers_reg_0/logictools_controllers_reg_0.xci
# IP: The module: 'logictools_controllers_reg_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_controllers_reg_0/logictools_controllers_reg_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_controllers_reg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_controllers_reg_0/logictools_controllers_reg_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_controllers_reg_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
