# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.srcs/sources_1/bd/logictools/ip/logictools_mb_axi_periph_imp_auto_cc_0/logictools_mb_axi_periph_imp_auto_cc_0.xci
# IP: The module: 'logictools_mb_axi_periph_imp_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_axi_periph_imp_auto_cc_0/logictools_mb_axi_periph_imp_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_axi_periph_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_axi_periph_imp_auto_cc_0/logictools_mb_axi_periph_imp_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_axi_periph_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.srcs/sources_1/bd/logictools/ip/logictools_mb_axi_periph_imp_auto_cc_0/logictools_mb_axi_periph_imp_auto_cc_0.xci
# IP: The module: 'logictools_mb_axi_periph_imp_auto_cc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_axi_periph_imp_auto_cc_0/logictools_mb_axi_periph_imp_auto_cc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_axi_periph_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_mb_axi_periph_imp_auto_cc_0/logictools_mb_axi_periph_imp_auto_cc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'logictools_mb_axi_periph_imp_auto_cc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
