# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/work/dev/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_ps7_0_axi_periph1_imp_s00_regslice_0/base_ps7_0_axi_periph1_imp_s00_regslice_0.xci
# IP: The module: 'base_ps7_0_axi_periph1_imp_s00_regslice_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/dev/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph1_imp_s00_regslice_0/base_ps7_0_axi_periph1_imp_s00_regslice_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_ps7_0_axi_periph1_imp_s00_regslice_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/work/dev/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph1_imp_s00_regslice_0/base_ps7_0_axi_periph1_imp_s00_regslice_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_ps7_0_axi_periph1_imp_s00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/work/dev/PYNQ/boards/Pynq-Z2/base/base/base.srcs/sources_1/bd/base/ip/base_ps7_0_axi_periph1_imp_s00_regslice_0/base_ps7_0_axi_periph1_imp_s00_regslice_0.xci
# IP: The module: 'base_ps7_0_axi_periph1_imp_s00_regslice_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/work/dev/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph1_imp_s00_regslice_0/base_ps7_0_axi_periph1_imp_s00_regslice_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_ps7_0_axi_periph1_imp_s00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/work/dev/PYNQ/boards/Pynq-Z2/base/base/base.gen/sources_1/bd/base/ip/base_ps7_0_axi_periph1_imp_s00_regslice_0/base_ps7_0_axi_periph1_imp_s00_regslice_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_ps7_0_axi_periph1_imp_s00_regslice_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
