set_property SRC_FILE_INFO {cfile:/home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.gen/sources_1/bd/logictools/ip/logictools_ilmb_v10_2/logictools_ilmb_v10_2_ooc.xdc rfile:../../../../../logictools.gen/sources_1/bd/logictools/ip/logictools_ilmb_v10_2/logictools_ilmb_v10_2_ooc.xdc id:1 order:EARLY scoped_inst:U0} [current_design]
set_property SRC_FILE_INFO {cfile:/home/its/yocto/petalinux/PYNQ/boards/Pynq-Z1/logictools/logictools/logictools.runs/logictools_ilmb_v10_2_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:55 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 10.000 -name LMB_Clk [get_ports LMB_Clk]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells U0]
