# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/its/tools/yocto/petal/pynq/boards/Pynq-Z2/base/pynq_z2_fresh/pynq_z2_fresh.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
# IP: The module: 'design_1_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/its/tools/yocto/petal/pynq/boards/Pynq-Z2/base/pynq_z2_fresh/pynq_z2_fresh.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/tools/yocto/petal/pynq/boards/Pynq-Z2/base/pynq_z2_fresh/pynq_z2_fresh.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/tools/yocto/petal/pynq/boards/Pynq-Z2/base/pynq_z2_fresh/pynq_z2_fresh.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/its/tools/yocto/petal/pynq/boards/Pynq-Z2/base/pynq_z2_fresh/pynq_z2_fresh.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xci
# IP: The module: 'design_1_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/its/tools/yocto/petal/pynq/boards/Pynq-Z2/base/pynq_z2_fresh/pynq_z2_fresh.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/tools/yocto/petal/pynq/boards/Pynq-Z2/base/pynq_z2_fresh/pynq_z2_fresh.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/its/tools/yocto/petal/pynq/boards/Pynq-Z2/base/pynq_z2_fresh/pynq_z2_fresh.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0/design_1_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
